# Generated by Django 2.2.7 on 2019-11-14 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wisdom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_title', models.CharField(max_length=50, verbose_name='Название мысли')),
                ('slug', models.SlugField(max_length=250, unique_for_date='published')),
                ('message', models.TextField(max_length=300, verbose_name='Содержание мысли')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
    ]
