# Generated by Django 2.2.7 on 2019-12-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='wisdom',
            name='author',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
